spring:
  application:
    name: deport-management
  datasource:
    url: jdbc:mysql://localhost:3306/deport_management_dev
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 'Munyaradzi@chowe'
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8022
