spring:
  application:
    name: deport-management
  datasource:
    url: jdbc:mysql://localhost:3306/deport_management_dev
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 'Munyaradzi@chowe'
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8022


clickatel:
  http:
    api:
      key: 'HQ9CGlaYSbGfNcY4OSyTAg=='
    send:
      url: 'https://platform.clickatell.com/messages/http/send?apiKey={apiKey}&to={to}&content={content}'
